FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

# Instala dependencias del SO y Python
COPY requirements.txt .
RUN apt-get update && apt-get install -y gcc default-libmysqlclient-dev pkg-config \
    && pip install --no-cache-dir -r requirements.txt \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Copia todo tu código y el entrypoint
COPY . .

# Usa el entrypoint para collectstatic + arranque
ENTRYPOINT ["./entrypoint.sh"]

EXPOSE 8000

