from .auth_views import *
from .perfil_views import *
from .relatos_views import *
from .amistad_views import *
from .buscadorUsuarios_views import *
from .comentarios_views import *
from .votos_views import *
from .estadisticas_views import *
from .home_views import *