# Generated by Django 5.2 on 2025-05-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookRoomAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participacionrelato',
            name='contenido_fragmento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participacionrelato',
            name='orden',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
