# Generated by Django 5.2 on 2025-05-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookRoomAPI', '0002_alter_usuario_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.PositiveSmallIntegerField(choices=[(1, 'administrador'), (3, 'moderador'), (2, 'cliente')], default=2),
        ),
    ]
