# Generated by Django 5.2 on 2025-05-15 16:46

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookRoomAPI', '0002_participacionrelato_contenido_fragmento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='votos',
            field=models.IntegerField(default=0, help_text='Contador neto de votos (positivo - negativo)'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='avatars/'),
        ),
    ]
