# Generated by Django 5.2 on 2025-04-15 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookRoomAPI', '0003_alter_usuario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilcliente',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL),
        ),
    ]
