# Generated by Django 5.2 on 2025-05-30 18:51

import cloudinary_storage.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookRoomAPI', '0003_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/img_avatar_ptmeu8', null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='avatars/'),
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('relato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='BookRoomAPI.relato')),
            ],
        ),
    ]
