# Generated by Django 5.2 on 2025-06-05 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookRoomAPI', '0004_alter_usuario_avatar_mensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='pdf_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
