# Generated by Django 5.2 on 2025-05-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookRoomAPI', '0004_comentariovoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentariovoto',
            name='valor',
            field=models.SmallIntegerField(choices=[(1, 'Voto-arriba'), (-1, 'VOoto-abajo')], default=0),
            preserve_default=False,
        ),
    ]
